version: '3.9'

services:
  db:
    image: postgres:15
    container_name: postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: pruebaAPI
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - backend

  api:
    build:
      context: .
    container_name: api_service
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: root
      DB_NAME: pruebaAPI
    ports:
      - "86:86"
    depends_on:
      - db
    networks:
      - backend

volumes:
  db_data:

networks:
  backend:
